name: rmgpgab-rutgers-agent-mastra-backend-us-east4-adamya-singh-rqlg
description: Build and deploy to Cloud Run service rutgers-agent-mastra-backend on push to "^master$"
github:
  owner: adamya-singh
  name: rutgers-soc-mastra-agent
  push:
    branch: ^master$
filename: cedar-mastra-agent/cloudbuild.backend.yaml
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
serviceAccount: projects/concise-foundry-465822-d7/serviceAccounts/496012954691-compute@developer.gserviceaccount.com
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - rutgers-agent-mastra-backend
